FROM openjdk:11
RUN addgroup --system paymentchain
RUN adduser --system admin --ingroup paymentchain
USER admin:paymentchain
VOLUME /tmp
ARG JAR_FILE=target/*.jar
ADD target/${JAR_FILE} app.jar
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]